"""Generates src/io/unicode_tables.inc: the Unicode letter and number ranges
the tokenizer's pre-tokenization rules need (\p{L} and \p{N} in the regexes
of GPT-2 and LLaMA 3 tokenizers), and the data for NFC normalization:
canonical combining classes, canonical decompositions and the pairs that
compose.

    python tools/gen_unicode_tables.py > src/io/unicode_tables.inc

Uses the Unicode version of the running Python's unicodedata module.
"""

import sys
import unicodedata


def ranges(predicate):
    out, start = [], None
    for cp in range(0x110000):
        inside = predicate(chr(cp))
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print(f"inline constexpr CodepointRange {name}[] = {{")
    for i in range(0, len(rs), 4):
        row = ", ".join(f"{{0x{a:04X}, 0x{b:04X}}}" for a, b in rs[i:i + 4])
        print(f"    {row},")
    print("};")


HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3  # decomposed algorithmically


def combining_classes():
    """(first, last, class) ranges of code points with a nonzero class."""
    out = []
    for cp in range(0x110000):
        cc = unicodedata.combining(chr(cp))
        if cc and out and out[-1][1] == cp - 1 and out[-1][2] == cc:
            out[-1] = (out[-1][0], cp, cc)
        elif cc:
            out.append((cp, cp, cc))
    return out


def decompositions():
    """(code point, full canonical decomposition) for every code point that
    has one, but Hangul syllables."""
    out = []
    for cp in range(0x110000):
        if HANGUL_FIRST <= cp <= HANGUL_LAST:
            continue
        d = unicodedata.normalize("NFD", chr(cp))
        if d != chr(cp):
            out.append((cp, [ord(c) for c in d]))
    return out


def compositions():
    """(first, second, composite), sorted: the primary composites, whose
    canonical decomposition is a pair that NFC puts back together (so not
    the composition exclusions)."""
    out = []
    for cp in range(0x110000):
        if HANGUL_FIRST <= cp <= HANGUL_LAST:
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(x, 16) for x in d.split()]
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            out.append((parts[0], parts[1], cp))
    return sorted(out)


def emit_nfc():
    ccs = combining_classes()
    print("inline constexpr CombiningClassRange kCombiningClasses[] = {")
    for i in range(0, len(ccs), 4):
        print("    " + ", ".join(f"{{0x{a:04X}, 0x{b:04X}, {c}}}" for a, b, c in ccs[i:i + 4]) + ",")
    print("};")
    print()
    decs = decompositions()
    data, entries = [], []
    for cp, seq in decs:
        entries.append((cp, len(data), len(seq)))
        data.extend(seq)
    print("inline constexpr char32_t kDecompositionData[] = {")
    for i in range(0, len(data), 8):
        print("    " + ", ".join(f"0x{c:04X}" for c in data[i:i + 8]) + ",")
    print("};")
    print()
    print("inline constexpr Decomposition kDecompositions[] = {")
    for i in range(0, len(entries), 4):
        print("    " + ", ".join(f"{{0x{a:04X}, {o}, {n}}}" for a, o, n in entries[i:i + 4]) + ",")
    print("};")
    print()
    comps = compositions()
    print("inline constexpr Composition kCompositions[] = {")
    for i in range(0, len(comps), 3):
        print("    " + ", ".join(f"{{0x{a:04X}, 0x{b:04X}, 0x{c:04X}}}" for a, b, c in comps[i:i + 3]) + ",")
    print("};")


def main():
    print(f"// Generated by tools/gen_unicode_tables.py from Unicode {unicodedata.unidata_version}.")
    print("// Do not edit by hand.")
    print()
    emit("kLetterRanges", ranges(lambda c: unicodedata.category(c).startswith("L")))
    print()
    emit("kNumberRanges", ranges(lambda c: unicodedata.category(c).startswith("N")))
    print()
    # The o200k split's [\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}] and [\p{Ll}\p{Lm}\p{Lo}\p{M}].
    upper = ("Lu", "Lt", "Lm", "Lo", "Mn", "Mc", "Me")
    lower = ("Ll", "Lm", "Lo", "Mn", "Mc", "Me")
    emit("kUpperishRanges", ranges(lambda c: unicodedata.category(c) in upper))
    print()
    emit("kLowerishRanges", ranges(lambda c: unicodedata.category(c) in lower))
    print()
    emit_nfc()
    return 0


if __name__ == "__main__":
    sys.exit(main())
