"""Generates src/io/unicode_tables.inc: the Unicode letter and number ranges
the tokenizer's pre-tokenization rules need (\p{L} and \p{N} in the regexes
of GPT-2 and LLaMA 3 tokenizers).

    python tools/gen_unicode_tables.py > src/io/unicode_tables.inc

Uses the Unicode version of the running Python's unicodedata module.
"""

import sys
import unicodedata


def ranges(predicate):
    out, start = [], None
    for cp in range(0x110000):
        inside = predicate(chr(cp))
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print(f"inline constexpr CodepointRange {name}[] = {{")
    for i in range(0, len(rs), 4):
        row = ", ".join(f"{{0x{a:04X}, 0x{b:04X}}}" for a, b in rs[i:i + 4])
        print(f"    {row},")
    print("};")


def main():
    print(f"// Generated by tools/gen_unicode_tables.py from Unicode {unicodedata.unidata_version}.")
    print("// Do not edit by hand.")
    print()
    emit("kLetterRanges", ranges(lambda c: unicodedata.category(c).startswith("L")))
    print()
    emit("kNumberRanges", ranges(lambda c: unicodedata.category(c).startswith("N")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
